eurovote/votes/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, SubmitField, RadioField, SelectField
from wtforms.validators import DataRequired, InputRequired

COUNTRY_CHOICES = [('Malta','Malta'),
                   ('Albania','Albania'),
                   ('Czech Republic','Czech Republic'),
                   ('Germany','Germany'),
                   ('Russia','Russia'),
                   ('Denmark','Denmark'),
                   ('San Marino','San Marino'),
                   ('North Macedonia','North Macedonia'),
                   ('Sweden','Sweden'),
                   ('Slovenia','Slovenia'),
                   ('Cyprus','Cyprus'),
                   ('Netherlands','Netherlands'),
                   ('Greece','Greece'),
                   ('Israel','Israel'),
                   ('Norway','Norway'),
                   ('United Kingdom','United Kingdom'),
                   ('Iceland','Iceland'),
                   ('Estonia','Estonia'),
                   ('Belarus','Belarus'),
                   ('Azerbaijan','Azerbaijan'),
                   ('France','France'),
                   ('Italy','Italy'),
                   ('Serbia','Serbia'),
                   ('Switzerland','Switzerland'),
                   ('Australia','Australia'),
                   ('Spain','Spain')]

SCORES = [(0,'0'),
          (1,'1'),
          (2,'2'),
          (3,'3'),
          (4,'4'),
          (5,'5')]

class VoteForm(FlaskForm):
   name = SelectField(label='Country', choices=COUNTRY_CHOICES,validators=[InputRequired()])
   song = RadioField('Song', coerce=int, choices=SCORES,validators=[InputRequired()])
   outfit = RadioField('Outfit', coerce=int, choices=SCORES,validators=[InputRequired()])
   performance = RadioField('Performance', coerce=int, choices=SCORES,validators=[InputRequired()])
   
   submit = SubmitField('Submit')

eurovote/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from eurovote import db, bcrypt
from eurovote.models import User
from eurovote.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from eurovote.users.utils import save_picture

users = Blueprint('users', __name__)

@users.route('/register',methods=['GET','POST']) 
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.','success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/',methods=['GET','POST'])
@users.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('You are now logged in.','success')
            return redirect(next_page) if next_page else redirect(url_for('votes.cast'))
        else:
            flash('Login unsuccessful. Please check email and password','danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    flash('You are now logged out.','success')
    return redirect(url_for('users.login'))

@users.route('/account',methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account info has been updated.','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pictures/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)

eurovote/votes/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required
from eurovote import db
from eurovote.models import Vote, User
from eurovote.votes.forms import VoteForm
from eurovote.votes.utils import Statistics, StatsTable
from sqlalchemy import desc, func
from sqlalchemy.sql import label

votes = Blueprint('votes', __name__)

@votes.route('/vote',methods=['GET','POST']) 
def cast():
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    form = VoteForm()

    # Search for all existing user votes, create list
    all_votes = Vote.query.filter_by(user_id=current_user.id).all()
    countries = []
    for vote in all_votes:
        countries.append(vote.name)

    # If existing vote, add tick
    keys = []
    vals = []
    for k,v in form.name.choices:
        keys.append(k)
        if v in countries:
            vals.append(v+'✓')
        else:
            vals.append(v)

    # Pass new choices to form
    choices_checked = list(zip(keys,vals))
    form.name.choices = choices_checked
    
    if form.validate_on_submit():
        # Current form submission
        cur = Vote.query.filter_by(user_id=current_user.id)\
                            .filter_by(name=form.name.data)\
                            .first()
        if cur:
            # Entry exists, update values
            current_user.votes[cur.id-1].song = form.song.data
            current_user.votes[cur.id-1].outfit = form.outfit.data
            current_user.votes[cur.id-1].performance = form.performance.data
            db.session.commit()
            if (form.name.data == 'Greece') or (form.name.data == 'Cyprus'):
                flash('Your vote has been updated. Ώπα!','success')
            else:
                flash('Your vote has been updated.','success')
            return redirect(url_for('votes.cast'))
        else:
            # No existing entry, add new
            cvote = Vote(name=form.name.data,
                         song=form.song.data,
                         outfit=form.outfit.data,
                         performance=form.performance.data,
                         user_id=current_user.id)
            db.session.add(cvote)
            db.session.commit()
            if (cvote.name == 'Greece') or (cvote.name == 'Cyprus'):
                flash('Your vote has been cast. Ώπα!','success')
            else:
                flash('Your vote has been cast.','success')
            return redirect(url_for('votes.cast'))
    return render_template('vote.html', title='Vote', form=form)


@votes.route('/stats',methods=['GET','POST']) 
def stat():
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    stat = Statistics()
    
    fields = ['song', 'outfit', 'performance']

    alltotals = db.session.query(Vote.name,
                                 label('total_score',
                                       func.sum(Vote.total_score(fields))),
                                 label('song_score',
                                       func.sum(Vote.total_score(['song']))),
                                 label('outfit_score',
                                       func.sum(Vote.total_score(['outfit']))),
                                 label('performance_score',
                                       func.sum(Vote.total_score(['performance']))),
    ).group_by('name').order_by(desc('total_score')).all()
    
    table = StatsTable(alltotals)
    
    total_score = db.session.query(Vote.name, label('total_score',func.sum(Vote.total_score(fields)))).group_by('name')
    
    stat.max_score = total_score.order_by(desc('total_score')).first()
    stat.min_score = total_score.order_by('total_score').first()

    total_song = db.session.query(Vote.name, label('total_score',func.sum(Vote.total_score(['song'])))).group_by('name')
    
    stat.max_song = total_song.order_by(desc('total_score')).first()
    stat.min_song = total_song.order_by('total_score').first()
    
    total_outfit = db.session.query(Vote.name, label('total_score',func.sum(Vote.total_score(['outfit'])))).group_by('name')
    
    stat.max_outfit = total_outfit.order_by(desc('total_score')).first()
    stat.min_outfit = total_outfit.order_by('total_score').first()

    total_perf = db.session.query(Vote.name, label('total_score',func.sum(Vote.total_score(['performance'])))).group_by('name')
    
    stat.max_performance = total_perf.order_by(desc('total_score')).first()
    stat.min_performance = total_perf.order_by('total_score').first()

    return render_template('stats.html', title='Statistics', stat=stat, table=table)

eurovote/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <p class="text-secondary">{{ current_user.email }}</p>
    </div>
  </div>
  <!-- FORM HERE -->
  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Current account info</legend>
      <div class="form-group">
	{{ form.username.label(class="form-control-label") }}
	{% if form.username.errors %}
	{{ form.username(class="form-control form-control-lg is-invalid") }}
	<div class="invalid-feedback">
	  {% for error in form.username.errors %}
	  <span>{{ error }}</span>
	  {% endfor %}
	</div>
	{% else %}
	{{ form.username(class="form-control form-control-lg") }}
	{% endif %}
      </div>
      <div class="form-group">
	{{ form.email.label(class="form-control-label") }}
	{% if form.email.errors %}
	{{ form.email(class="form-control form-control-lg is-invalid") }}
	<div class="invalid-feedback">
	  {% for error in form.email.errors %}
	  <span>{{ error }}</span>
	  {% endfor %}
	</div>
	{% else %}
	{{ form.email(class="form-control form-control-lg") }}
	{% endif %}
      </div>
      <div class="form-group">
	{{ form.picture.label() }}
	{{ form.picture(class="form-control-file") }}
	{% if form.picture.errors %}
	{% for error in form.picture.errors %}
	<span class="text-danger">{{ error }}</span></br>
	{% endfor %}
	{% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

eurovote/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
	  href="{{ url_for('static', filename='main.css')}}">
    <link rel="stylesheet" type="text/css"
	  href="{{ url_for('static', filename='radios-to-slider.css')}}">
    {% if title %}
    <title>Eurovote - {{ title }}</title>
    {%  else %}
    <title>Eurovote</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	<div class="container">
	  <img src="{{ url_for('static', filename='header.png')}}" style="width:125px;height:auto;">
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarToggle">
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
	      {% if current_user.is_authenticated %}
	      <a class="nav-item nav-link" href="{{ url_for('votes.cast') }}">Vote</a>
	      <a class="nav-item nav-link" href="{{ url_for('votes.stat') }}">Stats</a>
	      <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
	      <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
	      {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
	      {% endif %}
            </div> 
	  </div>
	</div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
	<div class="col-md-8">
	  {% with messages = get_flashed_messages(with_categories=True) %}
	  {% if messages %}
	  {% for category, message in messages %}
	  <div class="alert alert-{{ category }}">
	    {{ message }}
	  </div>
	  {% endfor %}
	  {% endif %}
	  {% endwith %}
	  {% block content %}{% endblock %}
	</div>
      </div>
    </main>
    <footer>
      <div class="row">
	<div class="col-md-12 col-sm-12">
	  <p class="text-center"><i><small>&copy; Eurovote 2019.</i></small></p>
	</div>
      </div>
      <a name="bottom" style="background:none;margin:none;padding:none;background-color:none;"></a>     
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='jquery.radios-to-slider.js')}}"></script>
    <script>
      $(document).ready(function(){
	  var radios = $("#radios").radiosToSlider({});
	  var radios1 = $("#radios1").radiosToSlider({});
	  var radios2 = $("#radios2").radiosToSlider({});
	  var radios2 = $("#radios3").radiosToSlider({});
      });
    </script>
  </body>
</html>

eurovote/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Login</legend>
      <div class="form-group">
	{{ form.email.label(class="form-control-label") }}
	{% if form.email.errors %}
	{{ form.email(class="form-control form-control-lg is-invalid") }}
	<div class="invalid-feedback">
	  {% for error in form.email.errors %}
	  <span>{{ error }}</span>
	  {% endfor %}
	</div>
	{% else %}
	{{ form.email(class="form-control form-control-lg") }}
	{% endif %}
      </div>
      <div class="form-group">
	{{ form.password.label(class="form-control-label") }}
	{% if form.password.errors %}
	{{ form.password(class="form-control form-control-lg is-invalid") }}
	<div class="invalid-feedback">
	  {% for error in form.password.errors %}
	  <span>{{ error }}</span>
	  {% endfor %}
	</div>
	{% else %}
	{{ form.password(class="form-control form-control-lg") }}
	{% endif %}
      </div>
      <div class="form-check">
	{{ form.remember(class="form-check-input") }}
	{{ form.remember.label(class="form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
</small>
</div>
{% endblock content %}

eurovote/templates/register.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Join Today</legend>
      <div class="form-group">
	{{ form.username.label(class="form-control-label") }}
	{% if form.username.errors %}
	{{ form.username(class="form-control form-control-lg is-invalid") }}
	<div class="invalid-feedback">
	  {% for error in form.username.errors %}
	  <span>{{ error }}</span>
	  {% endfor %}
	</div>
	{% else %}
	{{ form.username(class="form-control form-control-lg") }}
	{% endif %}
      </div>
      <div class="form-group">
	{{ form.email.label(class="form-control-label") }}
	{% if form.email.errors %}
	{{ form.email(class="form-control form-control-lg is-invalid") }}
	<div class="invalid-feedback">
	  {% for error in form.email.errors %}
	  <span>{{ error }}</span>
	  {% endfor %}
	</div>
	{% else %}
	{{ form.email(class="form-control form-control-lg") }}
	{% endif %}
      </div>
      <div class="form-group">
	{{ form.password.label(class="form-control-label") }}
	{% if form.password.errors %}
	{{ form.password(class="form-control form-control-lg is-invalid") }}
	<div class="invalid-feedback">
	  {% for error in form.password.errors %}
	  <span>{{ error }}</span>
	  {% endfor %}
	</div>
	{% else %}
	{{ form.password(class="form-control form-control-lg") }}
	{% endif %}
      </div>
      <div class="form-group">
	{{ form.confirm_password.label(class="form-control-label") }}
	{% if form.confirm_password.errors %}
	{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
	<div class="invalid-feedback">
	  {% for error in form.confirm_password.errors %}
	  <span>{{ error }}</span>
	  {% endfor %}
	</div>
	{% else %}
	{{ form.confirm_password(class="form-control form-control-lg") }}
	{% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
</small>
</div>
{% endblock content %}

eurovote/templates/stats.html
{% extends "layout.html" %}
{% block content %}
<legend class="border-bottom mb-4">Live scores</legend>
<div>
  <p>
    <b>Highest total score:</b>
    {{ stat.max_score.name }} with {{ stat.max_score.total_score}} points.
  </p>
  <p>
    <b>Lowest total score:</b>
    {{ stat.min_score.name }} with {{ stat.min_score.total_score }} points.
  </p>
  <p>
    <b>Best song:</b>
    {{ stat.max_song.name }} with {{ stat.max_song.total_score}} points.
  </p>
   <p>
     <b>Worst song:</b>
     {{ stat.min_song.name }} with {{ stat.min_song.total_score}} points.
  </p>
  <p>
    <b>Best outfit:</b>
    {{ stat.max_outfit.name }} with {{ stat.max_outfit.total_score}} points.
  </p>
  <p>
    <b>Worst outfit:</b>
    {{ stat.min_outfit.name }} with {{ stat.min_outfit.total_score}} points.
  </p>
  <p>
    <b>Best performance:</b>
    {{ stat.max_performance.name }} with {{ stat.max_performance.total_score}} points.
  </p>
  <p>
    <b>Worst performance:</b>
    {{ stat.min_performance.name }} with {{ stat.min_performance.total_score}} points.
  </p>
</div>
<div class="mt-4">
  {{ table }}
</div>
{% endblock content %}

eurovote/templates/vote.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <div class="media">
    <div class="media-body">
      <legend class="border-bottom mb-4">{{ current_user.username }}'s votes</legend>
    </div>
  </div>
  <!-- FORM HERE -->
  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <div class="form-group">
	{{ form.name.label(class="form-control-label") }}:
	{{ form.name(class="form-control form-control-lg") }}
      </div>
      {{ form.song.label(class="form-control-label") }}:
      <div id="radios1" class="form-group">
	<p>
	  {% for subfield in form.song %}
	  <tr>
	    <td>{{ subfield }}</td>
	    <td>{{ subfield.label }}</td>
	  </tr>
	  {% endfor %}
	</p>
      </div>
      {{ form.outfit.label(class="form-control-label") }}:
      <div id="radios2" class="form-group">
	<p>
	  {% for subfield in form.outfit %}
	  <tr>
	    <td>{{ subfield }}</td>
	    <td>{{ subfield.label }}</td>
	  </tr>
	  {% endfor %}
	</p>
      </div>
      {{ form.performance.label(class="form-control-label") }}:
      <div id="radios3" class="form-group">
	<p>
	  {% for subfield in form.performance %}
	  <tr>
	    <td>{{ subfield }}</td>
	    <td>{{ subfield.label }}</td>
	  </tr>
	  {% endfor %}
	</p>
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>


{% endblock content %}